-- We first create a SQL database to store the whatsapp group names and their descriptions to ensure there is no overlap in the group titles.
-- We then extract the phone numbers who are present in the whatsapp groups.
-- We extract the messages present in the whatapp groups and sort them accroding to the phone numbers they were sent from to ensure there is no disparity in the text messages.